"""empty message

Revision ID: bda33da6e2d9
Revises: ffe47d8d3a1e
Create Date: 2024-12-22 20:10:36.030342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bda33da6e2d9'
down_revision = 'ffe47d8d3a1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_constraint('votes_comment_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'comments', ['comment_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('votes_comment_id_fkey', 'comments', ['comment_id'], ['id'])

    # ### end Alembic commands ###
