on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build:
    name: build
    runs-on: self-hosted

    steps:
    - name: update repo
      uses: actions/checkout@v3

    - name: build-image
      run: |
        docker build -t manga-reader .

  deploy:
    name: deploy
    runs-on: self-hosted

    needs: build

    steps:
    - name: deploy-container
      run: |
        docker run --rm -d -p 8000:8000 --name manga-reader -v /var/www/kanwoo-manga.ru:/flask-app/ manga-reader
