on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

  prepare-environment:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Stop and remove containers, networks
        run: docker-compose down
      - name: Remove unused data
        run: docker system prune -a -f

  deploy:
    name: deploy
    runs-on: self-hosted

    needs: prepare-environment

    steps:
    - name: checkout repo
      uses: actions/checkout@v3

    - name: deploy-container
      run: |
        docker-compose up -d